### ISSUE TITLE
Inline output reader reduces performance for JSON benchmark

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.LinuxAsync#40]
See https://github.com/tmds/Tmds.LinuxAsync/issues/25#issuecomment-591415370

> I guess this is caused by multiple pipe writes for a single json reply (cfr dotnet/runtime#25059).

Verify this is the root cause, or find the root cause otherwise.

**Comment by tmds** [comment]
The `-p` argument determines whether the output reader uses an `IOQueue` (`-p true`) or is `Inline` (`-p false`).

We see this difference:
```
$ strace -qq -s 2000 -f -e sendto dotnet run -- -e epoll -p true
[pid 42773] sendto(128, "HTTP/1.1 200 OK\r\nDate: Thu, 27 Feb 2020 13:27:00 GMT\r\nServer: Kestrel\r\nTransfer-Encoding: chunked\r\n\r\nc\r\nHello World!\r\n0\r\n\r\n", 123, 0, NULL, 0) = 123
```
-> `IOQueue`: reply is sent as a single system call
```
$ strace -qq -s 2000 -f -e sendto dotnet run -- -e epoll -p false
[pid 42979] sendto(128, "HTTP/1.1 200 OK\r\nDate: Thu, 27 Feb 2020 13:27:17 GMT\r\nServer: Kestrel\r\nTransfer-Encoding: chunked\r\n\r\nc\r\nHello World!\r\n", 118, 0, NULL, 0) = 118
[pid 42979] sendto(128, "0\r\n\r\n", 5, 0, NULL, 0) = 5
```
-> `Inline`: reply is split over two system calls

So performance is better for the `IOQueue` because it makes a single syscall.
Probably performance will be best if we can make the `Inline` perform a single syscall.

This relates to https://github.com/dotnet/runtime/issues/25059: there is no distinction for the reader between WriteAsync (part of the response) and FlushAsync (entire response).

cc @davidfowl @halter73 @benaadams @adamsitnik

**Comment by davidfowl** [comment]
We don't write chunked in the JSON benchmark. Whatever test you're running you might want to change it to compare content length based responses to chunked responses.

**Comment by tmds** [comment]
> We don't write chunked in the JSON benchmark.

Indeed.
The two syscalls with `Inline` happen with this handler:

https://github.com/tmds/Tmds.LinuxAsync/blob/fbdb41a42ffc916e2c4c5509ce7d4b78aefa1c24/test/web/Startup.cs#L30-L33

The json handler generates a single syscall even with `Inline` scheduler

https://github.com/tmds/Tmds.LinuxAsync/blob/fbdb41a42ffc916e2c4c5509ce7d4b78aefa1c24/test/web/JsonMiddleware.cs#L20-L27

The syscalls are not the reason `Inline` performs about [10% worse](https://github.com/tmds/Tmds.LinuxAsync/issues/25#issuecomment-591415370) than `IOQueue` for TE JSON.

**Comment by tmds** [comment]
@adamsitnik let's try to figure this out by looking at the trace files. Can you run these benchmarks, and share results and trace files?
```
--path "/json" --arg "-e=epoll" --arg "-t=1" --arg "-s=false" --arg "-r=false" --arg "-c=true" --arg "-a=false" --arg "-i=true" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=1" --arg "-s=false" --arg "-r=false" --arg "-c=true" --arg "-a=false" --arg "-i=false" --connections 256
```

**Comment by adamsitnik** [comment]
```cmd
--path "/json" --arg "-e=epoll" --arg "-t=1" --arg "-s=false" --arg "-r=false" --arg "-c=true" --arg "-a=false" --arg "-i=true" --connections 256
```
```log
RequestsPerSecond:           390,269
Max CPU (%):                 98
WorkingSet (MB):             195
Avg. Latency (ms):           0.86
Startup (ms):                2
First Request (ms):          88
Latency (ms):                0.56
Total Requests:              5,893,061
Duration: (ms)               15,100
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             4,002
Published Size (KB):         1,060
SDK:                         5.0.100-preview.1.20106.1
Runtime:                     5.0.0-preview.2.20127.14
ASP.NET Core:                5.0.0-preview.2.20128.11
```
```cmd
--path "/json" --arg "-e=epoll" --arg "-t=1" --arg "-s=false" --arg "-r=false" --arg "-c=true" --arg "-a=false" --arg "-i=false" --connections 256
```
```log
RequestsPerSecond:           396,898
Max CPU (%):                 98
WorkingSet (MB):             193
Avg. Latency (ms):           0.92
Startup (ms):                2
First Request (ms):          93.74
Latency (ms):                0.66
Total Requests:              5,993,148
Duration: (ms)               15,100
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             4,001
Published Size (KB):         1,060
SDK:                         5.0.100-preview.1.20106.1
Runtime:                     5.0.0-preview.2.20127.14
ASP.NET Core:                5.0.0-preview.2.20128.11
```

**Comment by tmds** [comment]
Will you share the trace files on the gdrive?

**Comment by adamsitnik** [comment]
> Will you share the trace files on the gdrive?

Ups sorry, I forgot about it. I've re-run the benchmarks and uploaded the trace files to gdrive (same folder as recently)

```cmd
--path "/json" --arg "-e=epoll" --arg "-t=1" --arg "-s=false" --arg "-r=false" --arg "-c=true" --arg "-a=false" --arg "-i=true" --connections 256 --collect-trace
```
```log
RequestsPerSecond:           382,399
Max CPU (%):                 98
WorkingSet (MB):             189
Avg. Latency (ms):           0.92
Startup (ms):                1
First Request (ms):          116.87
Latency (ms):                0.34
Total Requests:              5,774,229
Duration: (ms)               15,100
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             6,502
Published Size (KB):         1,061
SDK:                         5.0.100-preview.1.20106.1
Runtime:                     5.0.0-preview.2.20127.14
ASP.NET Core:                5.0.0-preview.2.20128.11
```
```cmd
--path "/json" --arg "-e=epoll" --arg "-t=1" --arg "-s=false" --arg "-r=false" --arg "-c=true" --arg "-a=false" --arg "-i=false" --connections 256 --collect-trace
```
```log
RequestsPerSecond:           395,581
Max CPU (%):                 98
WorkingSet (MB):             191
Avg. Latency (ms):           0.88
Startup (ms):                2
First Request (ms):          98
Latency (ms):                0.4
Total Requests:              5,973,038
Duration: (ms)               15,100
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             4,502
Published Size (KB):         1,061
SDK:                         5.0.100-preview.1.20106.1
Runtime:                     5.0.0-preview.2.20127.14
ASP.NET Core:                5.0.0-preview.2.20128.11
```

**Comment by tmds** [comment]
I had a look at the trace files.

The difference in where time is spent are not that small, the total diff on RPS is also just 5%.
The main observation I made is that the slower version spends a bit more time doing synchronous receives.

When we inline the application code, the next recv is made a bit later. Maybe that increases chances of there being data, and reduces uses of epoll to receive the event, and batch it with other events.

**Comment by tmds** [comment]
Closing. Benchmarks (see https://github.com/tmds/Tmds.LinuxAsync/issues/78) will give us an overview of how this behaves with different schedulers, and `COMPlus_ThreadPool_UnfairSemaphoreSpinLimit=0`.
