### ISSUE TITLE
Use epoll/io_uring thread as output PipeScheduler

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.LinuxAsync#49]
The IOQueue PipeScheduler improves performance for output (https://github.com/tmds/Tmds.LinuxAsync/issues/40).

It would be interesting to see the difference in performance between an IOQueue PipeScheduler, and using the epoll/io_uring thread as PipeScheduler.

When we can use the epoll/io_uring thread as PipeScheduler we can batch the sends.

This requires an API to get the thread as a PipeScheduler from a Socket (e.g. `Socket.GetScheduler`), so we can use it as a reader scheduler on the output pipe:

https://github.com/tmds/Tmds.LinuxAsync/blob/601c88372d14ef5b784d574ec741d3fb5df6d666/src/Tmds.LinuxAsync.Transport/Internal/SocketConnection.cs#L78

We can change the `bool coalesceWrites` to an enum: Inline, IOQueue, SocketScheduler.

@antonfirsov do you want to implement this?

cc @adamsitnik @halter73 @davidfowl

**Comment by antonfirsov** [comment]
Sure, I need a ramp-up task here, so I will either look into this or into #51.

How would we realize such a feature in actual product code? `System.Net.Sockets` has no dependency on `System.IO.Pipelines` today. I suppose it will raise serious concerns, if we'd try to add it only because of Kestrel integration.

**Comment by tmds** [comment]
We should seek some opportunities to improve and quantify them.
In the end product owners decide what goes in the product.

I'm interested in knowing how much this brings, because custom Transports (like kestrel-linux-transport) leverage this.

Product implementation doesn't mean Socket needs to depend on Pipelines, the `PipeScheduler` is an abstraction for `void Schedule (Action<object> action, object state);`.

**Comment by tmds** [comment]
This is now implemented. We can now use the IOThread (that is: epoll/io_uring thread) as a PipeScheduler. When we do that, writes get batched using io_uring/AIO.

@adamsitnik let's run a benchmark to see the effect:
```
--path "/json" --arg "-e=epoll" --arg "-t=4" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=ioqueue" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=4" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=iothread" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=4" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=inline" --arg "-a=true" --arg "-w=false" --connections 256
```

**Comment by tmds** [comment]
> @adamsitnik let's run a benchmark to see the effect:

@antonfirsov maybe you can run these benchmarks?

**Comment by antonfirsov** [comment]
@tmds done, there is a new tab in my excel sheet + new traces:

https://microsoft-my.sharepoint.com/:f:/p/anfirszo/EkqER0svzQlJsYVH9EXVkosBElKc2q1K2wFI4TtC4L1mpg?e=hBMq37

**Comment by tmds** [comment]
Thanks, in the `iothread` case we're not fully loading CPU.
I haven't looked at the traces yet, but I guess moving sends to the epoll thread made it a bottleneck, and we need to increase `t`.

I've made https://github.com/tmds/Tmds.LinuxAsync/pull/61 to try improve perf for the scheduling.
After benchmarking that, we can run the `o=iothread` case for a range of `t`.

**Comment by tmds** [comment]
@antonfirsov let's run benchmarks for higher values of `t` now:

```
--path "/json" --arg "-e=epoll" --arg "-t=5" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=iothread" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=6" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=iothread" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=7" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=iothread" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=8" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=iothread" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=9" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=iothread" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=10" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=iothread" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=11" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=iothread" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=12" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=iothread" --arg "-a=true" --arg "-w=false" --connections 256
```

**Comment by antonfirsov** [comment]
Results:
| Threads | RPM     | latency |
|---------|---------|---------|
| 5       | 418,452 | 0.86    |
| 6       | 438,525 | 1.08    |
| 7       | 437,555 | 1.39    |
| 8       | 438,388 | 1.63    |
| 9       | 435,248 | 1.67    |
| 10      | 433,684 | 1.84    |
| 11      | 424,226 | 1.84    |
| 12      | 426,325 | 1.72    |

Details in the `Results-#49` subfolder. CPU's been always at max.

**Comment by tmds** [comment]
Thanks.

@adamsitnik @antonfirsov from all the benchmarking we've done so far, we haven't had a single benchmark that performed better when sends were batched with AIO on the epoll thread.

**Comment by tmds** [comment]
The best result we have in these measurements without batching sends is 443k (`--arg "-e=epoll" --arg "-t=4" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=ioqueue" --arg "-a=true" --arg "-w=false" --connections 256`).
And with batching sends it is 438k (`--path "/json" --arg "-e=epoll" --arg "-t=8" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-o=iothread" --arg "-a=true" --arg "-w=false" --connections 256
`).

So they are in fact not to far apart. Maybe if we can optimize the code, batching could have a positive effect. Though probably not that much.

For receives, we have been batching using `c=false` which has a positive impact. With `c=false`, the Kestrel ProcessReceives runs on the epoll thread. So there is no 'cost' to move to the thread.
It is interesting to check how receives perform if they have to be moved to the epoll thread also.

@antonfirsov @adamsitnik can you run these benchmarks?
```
--path "/json" --arg "-e=epoll" --arg "-t=1" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=2" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=3" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=4" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=4" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-a=true" --arg "-w=false" --connections 256
```

Kestrel always dispatches the http handling to the threadpool. If it weren't, the handler would run on the epoll thread and we'd have an easy time batching the sends. The reason it runs on threadpool is to deal with performance accepting connections. If the processing continues on the iothread, no new connections can be accepted, so less performance accepting new connections. On Linux other threads could be accepting connections in the meanwhile by using `SO_REUSEPORT`. I'm mentioning for reference, this is out-of-scope for what we're doing here.

**Comment by antonfirsov** [comment]
Done, see new tab on my sheet. RPS values in order:
```
308,504
385,363
392,242
392,382
432,061
```

**Comment by tmds** [comment]
Thank you. None of the `r=true` manage to max CPU, let's increase `t` further.
And also run a benchmark where we don't batch receives.
```
--path "/json" --arg "-e=epoll" --arg "-t=5" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=6" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=7" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=8" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=9" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=10" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=11" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
--path "/json" --arg "-e=epoll" --arg "-t=12" --arg "-s=false" --arg "-r=true" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256

--path "/json" --arg "-e=epoll" --arg "-t=1" --arg "-s=false" --arg "-r=false" --arg "-c=true" --arg "-a=true" --arg "-w=false" --connections 256
```

**Comment by tmds** [comment]
> we haven't had a single benchmark that performed better when sends were batched with AIO on the epoll thread.

@adamsitnik @antonfirsov to have an idea of potential gain of batching sends, we can see what happens when we turn off send batching in klt:
```
--path "/json" --arg "-e=linuxtransport" --arg "-t=4" --arg "-s=true" --connections 256
--path "/json" --arg "-e=linuxtransport" --arg "-t=4" --arg "-s=false" --connections 256
```

**Comment by adamsitnik** [comment]
```cmd
--path "/json" --arg "-e=linuxtransport" --arg "-t=4" --arg "-s=true" --connections 256
```
```log
RequestsPerSecond:           408,346
Max CPU (%):                 94
WorkingSet (MB):             180
Avg. Latency (ms):           0.7
Startup (ms):                2
First Request (ms):          102.75
Latency (ms):                0.32
Total Requests:              6,165,719
Duration: (ms)               15,100
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             7,502
Published Size (KB):         1,138
SDK:                         5.0.100-preview.2.20120.3
Runtime:                     5.0.0-preview.2.20155.3
ASP.NET Core:                5.0.0-preview.3.20167.1
```
```cmd
--path "/json" --arg "-e=linuxtransport" --arg "-t=4" --arg "-s=false" --connections 256
```
```log
RequestsPerSecond:           373,399
Max CPU (%):                 99
WorkingSet (MB):             178
Avg. Latency (ms):           1.35
Startup (ms):                2
First Request (ms):          94.55
Latency (ms):                0.37
Total Requests:              5,638,185
Duration: (ms)               15,100
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             4,502
Published Size (KB):         1,138
SDK:                         5.0.100-preview.2.20120.3
Runtime:                     5.0.0-preview.2.20155.3
ASP.NET Core:                5.0.0-preview.3.20167.1
```

traces uploaded to `18_03_2020_linuxtransport` subfolder

**Comment by tmds** [comment]
Even not yet at 100% cpu, batching the sends (`s=true`) performs +10% better.
So we can't dismiss the concept.
