### ISSUE TITLE
Explore reducing the locking in Queue

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.LinuxAsync#52]
The lock in Queue class serves these purposes:
- allow multiple operations, though the typical case is there is at most 1 element
- allow async cancellation a single operations, or all operations on dispose
- for epoll, avoid loosing events from epoll

I'm not sure if there is much to gain by trying to replace locking with other synchronization primitives, because the lock _should_ not be contended.

cc @adamsitnik @antonfirsov

**Comment by tkp1n** [comment]
Regarding io_uring:

I added a package `IoUring.Concurrent` to the usual [MyGet feed](https://www.myget.org/feed/tkp1n/package/nuget/IoUring.Concurrent). It primarily features the `ConcurrentRing` class (as opposed to the non-thread-safe `Ring` in the `IoUring` package).

`ConcurrentRing` allows you to prepare `SQE`s and consume `CQE`s without external locking. Internally a `Volatile.Read` + `Interlocked.CompareExchange` loop is used to ensure correctness. `SubmitAndWait` is internally synchronized using a lock.

The API of `ConcurrentRing` is slightly more involved as the following example demonstrates:

```csharp
// using Ring
var r = new Ring(8);
r.PrepareNop();

// using ConcurrentRing
var cr = new ConcurrentRing(8);
if (!cr.TryAcquireSubmission(out Submission submission)) throw null;
submission.PrepareNop();
submission.Release();
```

After a successful `TryAcquireSubmission` the `Submission` must be immediately "prepared" and "released", as all `Submission`s past a non-released `Submission` will not be submitted to the kernel during the next `SubmitAndWait`.

I assume this will help you to further reduce locking in your code. Let me know if you run into issues or need help with experiments.

**Comment by tmds** [comment]
@tkp1n can you add your comment to https://github.com/tmds/Tmds.LinuxAsync/issues/51? I'll hide it here. I don't think there is a way for me to move it.

**Comment by tmds** [comment]
I'm going to take a look at this, mostly for the fun/challenge of it.

It's not something that shows up as a bottleneck in the traces, but maybe there is still a measurable gain.

I'm going to focus on epoll. I'm not sure if the same code will be usable for io_uring.

**Comment by tmds** [comment]
Fixed in https://github.com/tmds/Tmds.LinuxAsync/pull/76
